version: '3.7'
services:
  redis-app:
    container_name: redis-app
    hostname: redis-app-host
    build : redis
    command: ["redis-server", "--protected-mode", "no"]
    ports:
       - 6379:6379
    volumes:
      - /var/run/appscope:/var/run/appscope
    restart: unless-stopped

  top-app:
    container_name: top-app
    image: ubuntu:18.04
    command: ["top"]
    environment:
      - TERM=xterm
    tty: true
    volumes:
      - /var/run/appscope:/var/run/appscope
    restart: unless-stopped

  java-app:
    container_name: java-app
    build : javaserver
    ports:
       - 8789:8789
    volumes:
      - /var/run/appscope:/var/run/appscope

  oomdemo-1:
    container_name: oomdemo-1
    build: oomdemo
    mem_limit: 300m
    restart: unless-stopped

  edge-node1:
    container_name: edge-node1
    hostname: edge-node1-host
    image: cribl/cribl:latest
    privileged: true
    environment:
      - CRIBL_EDGE=1
      - CRIBL_DIST_MODE=managed-edge
      - CRIBL_DIST_MASTER_URL=tls://${CLOUD_TOKEN}@${CLOUD_LEADER_HOSTNAME}:4200?group=${CLOUD_FLEET_NAME}
    volumes:
      - /var/run/appscope:/var/run/appscope
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
